---
AWSTemplateFormatVersion: 2010-09-09
Description: Laravel RDS MySQL Database Instance

Parameters:
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    AllowedValues:
      - db.t2.micro
      - db.t2.small
      - db.t2.medium
    Description: Database Instance Class
  DBAllocatedStorage:
    Type: Number
    Default: 20
    Description: Allocated Storage
  DBInstanceIdentifier:
    Type: String
    Default: "test-rds"
    Description: Database Instance Name
  DBName:
    Type: String
    Default: "laravel"
    Description: Database Name
  DBMasterUsername:
    Type: String
    Default: "laravel"
    Description: Database Master Username
  DBMasterUserPassword:
    Type: String
    Default: "password"
    Description: Database Master User Password
  VPC:
    Description: Choose which VPC this RDS instance should be deployed to
    Type: AWS::EC2::VPC::Id
  VPCSubnets:
    Description: Choose which VPC subnets this RDS instance can be deployed to
    Type: List<AWS::EC2::Subnet::Id>

Resources:

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VPC
      GroupDescription: Inbound and Outbound rules for RDS MySQL Service
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
        CidrIp: 172.31.0.0/16
        Description: "MySQL access from VPC"

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      SubnetIds: !Ref VPCSubnets
      DBSubnetGroupDescription: "Subnet Group for Laravel DB Instance(s)"

  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Ref DBInstanceIdentifier
      DBName: !Ref DBName
      StorageType: "gp2"
      AllocatedStorage: !Ref DBAllocatedStorage
      DBInstanceClass: !Ref DBInstanceClass
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: "MySQL"
      EngineVersion: "5.7.39"
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
    DeletionPolicy: "Snapshot"

Outputs:
  EndpointAddress:
    Description: Endpoint Address of the RDS MySQL Database Instance
    Value:
      Fn::GetAtt:
      - DBInstance
      - Endpoint.Address
  EndpointPort:
    Description: Endpoint Port of the RDS MySQL Database Instance
    Value:
      Fn::GetAtt:
      - DBInstance
      - Endpoint.Port
